daemonize = true
max_history = 50
history_file_path = "/home/beppe/.cache/clipcat/clipcat-history"
pid_file = "/run/user/1000/clipcatd.pid"

[log]
file_path = "/home/beppe/.config/clipcat/log.log"
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"

[watcher]
enable_clipboard = true
enable_primary = true
sensitive_x11_atoms = ["x-kde-passwordManagerHint"]
denied_text_regex_patterns = []
filter_text_min_length = 1
filter_text_max_length = 20000000
capture_image = true
filter_image_max_size = 5242880



[grpc]
enable_http = true
enable_local_socket = true
host = "127.0.0.1"
port = 45045
local_socket = "/run/user/1000/clipcat/grpc.sock"

[dbus]
enable = true
identifier = "instance-0"

[desktop_notification]
enable = true
timeout_ms = 1000
long_plaintext_length = 2000



